### PR TITLE
Updated Private API for macOS Mojave

### PR DESCRIPTION
**Pull request by latenitefilms**
- Updated Private API for macOS Mojave

### CODE REVIEW

**Comment by asmagill** [comment]
Does this break working in 10.12/13?

**Comment by latenitefilms** [comment]
No, it should still be backwards compadible.

**Comment by asmagill** [comment]
Completely forgot about this, @latenitefilms, I'll do a build this weekend and maybe see if I can polish up the examples at least since there seems to be some renewed interest (at least from one person) in this.

I do want to concentrate on `hs.text` and `hs.axuielement`, but sometimes its nice to take a break and do something else for a bit :-)

**Comment by latenitefilms** [comment]
No worries at all!

The documentation for `hs._asm.undocumented.touchbar` is actually pretty good from memory. Once this pull request is pulled in, I reckon this extension is essentially ready to be merged into Hammerspoon.

The only major issue we've come across is that it [doesn't work with the 16-inch MacBook Pro](https://github.com/asmagill/hammerspoon_asm.undocumented/issues/10), and we haven't been able to work out why yet.

**Comment by asmagill** [comment]
touchbar moved to git submodule and this pull was manually applied. closing. Reopen new pull at https://github.com/asmagill/hs._asm.undocumented.touchbar if additional changes are required or something appears to be missing in the new submodule.

**Pull request closed without merging**
